name = "my-okrs"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "strategy-plan"
database_id = "db664593-a2f1-4b0f-8ae6-0bd112ff9099"
