import { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlignLeft, ArrowDownUp, BarChart3, Bell, Building2, CalendarDays,
  Check, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, CircleHelp, Clock3,
  Compass, Filter, Flag, GitBranch, Goal, Home, LayoutDashboard, List, Menu,
  MoreHorizontal, Plus, Search, Settings, Sparkles, Target, TreePine, Users, X, Zap
} from 'lucide-react';

const STORAGE_KEY = 'northstar-okr-data-v1';
const teams = {
  Company: { color: '#6046db', soft: '#eeeafd' }, Product: { color: '#147b68', soft: '#e2f5ef' },
  Growth: { color: '#b55b14', soft: '#fff0df' }, People: { color: '#b43f6b', soft: '#fde8ef' },
  Revenue: { color: '#2670b7', soft: '#e6f1fc' }
};
const initialGoals = [
  { id:'g1', title:'Build the category-defining AI workspace', description:'Create a product experience customers cannot imagine working without.', team:'Company', owner:'Maya Chen', initials:'MC', progress:68, status:'On track', period:'Q3 2026', parentId:null, updated:'2h ago', keyResults:[{title:'Reach 45% weekly active usage',value:72},{title:'Increase NPS to 62',value:64},{title:'Ship 3 AI workflow capabilities',value:67}], initiatives:['AI command center','Context-aware recommendations','Mobile workspace refresh'] },
  { id:'g2', title:'Deliver an exceptional activation experience', description:'Help every new team reach meaningful value in their first session.', team:'Product', owner:'Noah Williams', initials:'NW', progress:61, status:'On track', period:'Q3 2026', parentId:'g1', updated:'Yesterday', keyResults:[{title:'Reduce time-to-value below 8 minutes',value:58},{title:'Raise onboarding completion to 80%',value:64}], initiatives:['Guided workspace setup','Role-based templates','Activation analytics'] },
  { id:'g3', title:'Create a repeatable growth engine', description:'Build efficient, measurable acquisition loops across priority segments.', team:'Growth', owner:'Sofia Patel', initials:'SP', progress:44, status:'At risk', period:'Q3 2026', parentId:'g1', updated:'3h ago', keyResults:[{title:'Generate 2,500 product-qualified leads',value:48},{title:'Improve organic conversion by 25%',value:40}], initiatives:['Customer story program','SEO topic clusters','Partner launch playbook'] },
  { id:'g4', title:'Become the best place to do career-defining work', description:'Create an environment where ambitious people thrive and grow.', team:'People', owner:'Avery Johnson', initials:'AJ', progress:76, status:'On track', period:'Q3 2026', parentId:null, updated:'Mon', keyResults:[{title:'Reach 85% engagement score',value:82},{title:'Fill 90% of key roles on time',value:70}], initiatives:['Manager excellence program','Career architecture rollout','Hiring bar calibration'] },
  { id:'g5', title:'Scale leadership capability', description:'Equip every manager to lead with clarity, empathy, and accountability.', team:'People', owner:'Amelia Davis', initials:'AD', progress:52, status:'At risk', period:'Q3 2026', parentId:'g4', updated:'Fri', keyResults:[{title:'100% manager coaching completion',value:61},{title:'Increase manager effectiveness to 4.3',value:43}], initiatives:['Monthly manager labs','Leadership 360 reviews'] },
  { id:'g6', title:'Accelerate enterprise expansion', description:'Win and grow strategic accounts with a focused commercial motion.', team:'Revenue', owner:'Ethan Brooks', initials:'EB', progress:31, status:'Off track', period:'Q3 2026', parentId:null, updated:'4h ago', keyResults:[{title:'Close $1.8M enterprise ARR',value:28},{title:'Grow expansion pipeline to $4M',value:34}], initiatives:['Enterprise account pods','Executive sponsor program','Security readiness sprint'] },
];

const statusTone = { 'On track':'green', 'At risk':'amber', 'Off track':'red', 'Not started':'gray' };
const navItems = [{icon:Home,label:'Home'},{icon:Target,label:'Goals',active:true},{icon:Activity,label:'Check-ins'},{icon:BarChart3,label:'Insights'}];

function App(){
  const [goals,setGoals] = useState(()=>{ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)) || initialGoals}catch{return initialGoals} });
  const [view,setView] = useState('Cascade');
  const [query,setQuery] = useState('');
  const [teamFilter,setTeamFilter] = useState('All teams');
  const [expanded,setExpanded] = useState(new Set(['g1','g4','g6']));
  const [selected,setSelected] = useState(null);
  const [modal,setModal] = useState(false);
  const [sidebar,setSidebar] = useState(false);
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(goals)),[goals]);
  const visible = useMemo(()=>goals.filter(g=>(teamFilter==='All teams'||g.team===teamFilter) && (`${g.title} ${g.owner} ${g.team}`).toLowerCase().includes(query.toLowerCase())),[goals,query,teamFilter]);
  const avg=Math.round(goals.reduce((a,g)=>a+g.progress,0)/goals.length), onTrack=goals.filter(g=>g.status==='On track').length;
  const toggle=id=>setExpanded(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n});
  const addGoal=(goal)=>{setGoals(prev=>[...prev,{...goal,id:`g${Date.now()}`,initials:goal.owner.split(' ').map(x=>x[0]).join('').slice(0,2),updated:'Just now',keyResults:[{title:goal.keyResult,value:Number(goal.progress)}],initiatives:goal.initiatives.split('\n').filter(Boolean)}]);setModal(false)};
  return <div className="app-shell">
    <Sidebar open={sidebar} close={()=>setSidebar(false)}/>
    <main className="main">
      <header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setSidebar(true)}><Menu size={20}/></button><div className="crumb"><span>Goals</span><ChevronRight size={14}/><strong>Explorer</strong></div><div className="top-actions"><button className="icon-button"><Search size={19}/></button><button className="icon-button notification"><Bell size={19}/><i/></button><div className="avatar">MC</div></div></header>
      <section className="content">
        <div className="hero"><div><div className="eyebrow"><Sparkles size={14}/> STRATEGY EXECUTION</div><h1>Goals Explorer</h1><p>See how every team’s work connects to what matters most.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> New goal</button></div>
        <div className="metrics">
          <Metric icon={Target} label="Active goals" value={goals.length} detail="Across 5 teams" tone="violet"/>
          <Metric icon={Activity} label="Average progress" value={`${avg}%`} detail="+6% this month" tone="blue"/>
          <Metric icon={Check} label="On track" value={`${onTrack}/${goals.length}`} detail={`${Math.round(onTrack/goals.length*100)}% healthy`} tone="green"/>
          <Metric icon={Clock3} label="Quarter remaining" value="31 days" detail="Ends Sep 30" tone="orange"/>
        </div>
        <div className="workspace">
          <div className="workspace-head">
            <div className="view-tabs">{[[GitBranch,'Cascade'],[TreePine,'Tree'],[List,'List']].map(([Icon,name])=><button key={name} className={view===name?'active':''} onClick={()=>setView(name)}><Icon size={17}/>{name}</button>)}</div>
            <div className="period"><button className="icon-button"><ChevronLeft size={17}/></button><CalendarDays size={16}/><b>Q3 2026</b><button className="icon-button"><ChevronRight size={17}/></button></div>
          </div>
          <div className="toolbar"><div className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search goals, owners, or teams..."/>{query&&<button onClick={()=>setQuery('')}><X size={15}/></button>}</div><div className="toolbar-right"><label className="select-wrap"><Users size={16}/><select value={teamFilter} onChange={e=>setTeamFilter(e.target.value)}><option>All teams</option>{Object.keys(teams).map(t=><option key={t}>{t}</option>)}</select><ChevronDown size={14}/></label><button className="filter-button"><Filter size={16}/> Filters <span>2</span></button><button className="icon-button"><ArrowDownUp size={17}/></button><button className="icon-button"><MoreHorizontal size={18}/></button></div></div>
          {view==='Cascade'&&<Cascade goals={visible} expanded={expanded} toggle={toggle} select={setSelected}/>} 
          {view==='Tree'&&<TreeView goals={visible} select={setSelected}/>} 
          {view==='List'&&<ListView goals={visible} select={setSelected}/>} 
        </div>
      </section>
    </main>
    {modal&&<GoalModal goals={goals} close={()=>setModal(false)} save={addGoal}/>} 
    {selected&&<GoalDrawer goal={goals.find(g=>g.id===selected)} close={()=>setSelected(null)} update={(id,data)=>setGoals(gs=>gs.map(g=>g.id===id?{...g,...data,updated:'Just now'}:g))}/>} 
  </div>
}

function Sidebar({open,close}){return <><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark"><Compass size={21}/></div><div><b>Northstar</b><span>OKR workspace</span></div><button className="mobile-close" onClick={close}><X/></button></div><nav>{navItems.map(({icon:Icon,label,active})=><button key={label} className={active?'active':''}><Icon size={19}/><span>{label}</span>{label==='Goals'&&<em>6</em>}</button>)}</nav><div className="nav-label">WORKSPACE</div><nav><button><Building2 size={19}/><span>Teams</span></button><button><CalendarDays size={19}/><span>Cycles</span></button><button><LayoutDashboard size={19}/><span>Reports</span></button></nav><div className="sidebar-card"><div className="card-icon"><Zap size={17}/></div><b>Quarterly review</b><p>Your Q3 review is in 5 days. Make sure every goal is current.</p><button>Review check-ins</button></div><div className="sidebar-foot"><button><CircleHelp size={19}/>Help & resources</button><button><Settings size={19}/>Settings</button><div className="profile"><div className="avatar">MC</div><div><b>Maya Chen</b><span>Workspace admin</span></div><MoreHorizontal size={18}/></div></div></aside>{open&&<div className="scrim" onClick={close}/>}</>}
function Metric({icon:Icon,label,value,detail,tone}){return <article className="metric"><div className={`metric-icon ${tone}`}><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}

function Cascade({goals,expanded,toggle,select}){
 const roots=goals.filter(g=>!g.parentId||!goals.some(x=>x.id===g.parentId));
 const children=id=>goals.filter(g=>g.parentId===id);
 const rows=[]; roots.forEach(root=>{rows.push({g:root,level:0});if(expanded.has(root.id))children(root.id).forEach(c=>rows.push({g:c,level:1}))});
 return <div className="cascade table-scroll"><div className="cascade-grid header-row"><div>Name</div><div>Team</div><div>Owner</div><div>Progress</div><div>Status</div><div/></div>{rows.map(({g,level})=>{const kids=children(g.id);return <div className={`cascade-grid data-row level-${level}`} key={g.id} onClick={()=>select(g.id)}><div className="goal-name" style={{paddingLeft:level*34+18}}>{kids.length?<button onClick={e=>{e.stopPropagation();toggle(g.id)}}>{expanded.has(g.id)?<ChevronDown/>:<ChevronRight/>}</button>:<span className="row-spacer"/>}<div className={`type-icon ${level?'objective':'parent'}`}>{level?<Target size={15}/>:<Flag size={15}/>}</div><div><b>{g.title}</b><small>{level?`${g.keyResults.length} key results · ${g.initiatives.length} initiatives`:`${kids.length} aligned objective${kids.length!==1?'s':''}`}</small></div></div><div><TeamPill team={g.team}/></div><div><Owner goal={g}/></div><div><Progress value={g.progress}/></div><div><Status value={g.status}/></div><div><MoreHorizontal size={17}/></div></div>})}{!rows.length&&<Empty/>}<button className="add-inline" onClick={()=>document.querySelector('.primary').click()}><Plus size={16}/> Add goal</button></div>
}
function TreeView({goals,select}){const roots=goals.filter(g=>!g.parentId||!goals.some(x=>x.id===g.parentId));return <div className="tree-view"><div className="tree-intro"><GitBranch size={18}/><div><b>Alignment map</b><span>Follow the line from company strategy to team execution.</span></div></div><div className="tree-canvas">{roots.map(root=><div className="tree-branch" key={root.id}><GoalCard goal={root} select={select} parent/>{goals.filter(g=>g.parentId===root.id).length>0&&<div className="tree-children">{goals.filter(g=>g.parentId===root.id).map(g=><GoalCard key={g.id} goal={g} select={select}/>)}</div>}</div>)}</div>{!roots.length&&<Empty/>}</div>}
function GoalCard({goal,select,parent}) {return <button className={`goal-card ${parent?'parent':''}`} onClick={()=>select(goal.id)}><div className="goal-card-top"><TeamPill team={goal.team}/><MoreHorizontal size={17}/></div><h3>{goal.title}</h3><p>{goal.description}</p><div className="goal-card-bottom"><Owner goal={goal} compact/><Progress value={goal.progress} compact/></div></button>}
function ListView({goals,select}){return <div className="list-view"><div className="list-header"><span>Objective</span><span>Owner</span><span>Cycle</span><span>Progress</span><span>Status</span></div>{goals.map(g=><button className="list-row" key={g.id} onClick={()=>select(g.id)}><div className="list-objective"><div className="type-icon objective"><Target size={15}/></div><div><b>{g.title}</b><small>{g.keyResults.length} key results · Updated {g.updated}</small></div></div><Owner goal={g}/><span className="cycle">{g.period}</span><Progress value={g.progress}/><Status value={g.status}/></button>)}{!goals.length&&<Empty/>}</div>}
function TeamPill({team}){const t=teams[team]||teams.Company;return <span className="team-pill" style={{color:t.color,background:t.soft}}><i style={{background:t.color}}/>{team}</span>}
function Owner({goal,compact}) {return <span className={`owner ${compact?'compact':''}`}><i>{goal.initials}</i>{!compact&&goal.owner}</span>}
function Progress({value,compact}){const color=value>=60?'#25a77c':value>=40?'#e7a52b':'#e05a47';return <div className={`progress ${compact?'compact':''}`}><div><i style={{width:`${value}%`,background:color}}/></div><b>{value}%</b></div>}
function Status({value}){return <span className={`status ${statusTone[value]}`}><i/>{value}</span>}
function Empty(){return <div className="empty"><Search size={26}/><b>No goals found</b><span>Try adjusting your search or filters.</span></div>}

function GoalDrawer({goal,close,update}){const [progress,setProgress]=useState(goal.progress);if(!goal)return null;return <><div className="drawer-scrim" onClick={close}/><aside className="drawer"><div className="drawer-head"><span className="drawer-label"><Target size={15}/> OBJECTIVE</span><button className="icon-button" onClick={close}><X size={19}/></button></div><div className="drawer-title"><TeamPill team={goal.team}/><h2>{goal.title}</h2><p>{goal.description}</p></div><div className="drawer-meta"><div><span>Owner</span><Owner goal={goal}/></div><div><span>Cycle</span><b><CalendarDays size={15}/>{goal.period}</b></div><div><span>Health</span><Status value={goal.status}/></div></div><section className="drawer-section"><div className="section-head"><div><b>Overall progress</b><span>Update progress to keep your team aligned.</span></div><strong>{progress}%</strong></div><input className="range" type="range" min="0" max="100" value={progress} onChange={e=>setProgress(Number(e.target.value))}/><button className="save-progress" onClick={()=>update(goal.id,{progress,status:progress>=60?'On track':progress>=40?'At risk':'Off track'})}>Save check-in</button></section><section className="drawer-section"><div className="section-head"><div><b>Key results</b><span>Measurable outcomes for this objective.</span></div><button className="icon-button"><Plus size={17}/></button></div><div className="kr-list">{goal.keyResults.map((kr,i)=><div className="kr" key={i}><div className="kr-index">{i+1}</div><div><b>{kr.title}</b><Progress value={kr.value}/></div></div>)}</div></section><section className="drawer-section"><div className="section-head"><div><b>Initiatives</b><span>The work driving this objective forward.</span></div><button className="icon-button"><Plus size={17}/></button></div><div className="initiative-list">{goal.initiatives.map((x,i)=><div key={i}><span><Zap size={15}/></span><b>{x}</b><em>{i%2?'In progress':'Planned'}</em></div>)}</div></section></aside></>}
function GoalModal({goals,close,save}){const [form,setForm]=useState({title:'',description:'',team:'Product',owner:'',period:'Q3 2026',progress:0,status:'Not started',parentId:'',keyResult:'',initiatives:''});const change=e=>setForm({...form,[e.target.name]:e.target.value});const submit=e=>{e.preventDefault();if(form.title&&form.owner&&form.keyResult)save({...form,progress:Number(form.progress),parentId:form.parentId||null})};return <div className="modal-wrap"><div className="modal"><div className="modal-head"><div><span className="drawer-label"><Sparkles size={14}/> NEW OBJECTIVE</span><h2>Create a goal</h2><p>Define the outcome, owner, and work that will move it forward.</p></div><button className="icon-button" onClick={close}><X/></button></div><form onSubmit={submit}><label className="full"><span>Objective title</span><input autoFocus required name="title" value={form.title} onChange={change} placeholder="What do you want to accomplish?"/></label><label className="full"><span>Description</span><textarea name="description" value={form.description} onChange={change} placeholder="Why does this objective matter?"/></label><label><span>Team</span><select name="team" value={form.team} onChange={change}>{Object.keys(teams).map(t=><option key={t}>{t}</option>)}</select></label><label><span>Owner</span><input required name="owner" value={form.owner} onChange={change} placeholder="Full name"/></label><label><span>Cycle</span><select name="period" value={form.period} onChange={change}><option>Q3 2026</option><option>Q4 2026</option><option>Annual 2026</option></select></label><label><span>Align to</span><select name="parentId" value={form.parentId} onChange={change}><option value="">Company-level goal</option>{goals.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></label><label className="full"><span>First measurable key result</span><input required name="keyResult" value={form.keyResult} onChange={change} placeholder="e.g. Increase activation rate from 42% to 65%"/></label><label className="full"><span>Initiatives <em>one per line</em></span><textarea name="initiatives" value={form.initiatives} onChange={change} placeholder={'Redesign onboarding flow\nLaunch guided templates'}/></label><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><Plus size={17}/> Create goal</button></div></form></div></div>}
export default App;
