import { useEffect, useMemo, useState } from 'react';
import {
  Activity, ArrowDownUp, BarChart3, Bell, Building2, CalendarDays, Check,
  ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Clock3, Compass, Filter,
  Flag, GitBranch, Home, LayoutDashboard, List, Menu, MoreHorizontal, Pencil,
  Plus, Save, Search, Settings, Sparkles, Target, Trash2, TreePine, Users, X, Zap
} from 'lucide-react';

const STORAGE_KEY = 'northstar-okr-data-v1';
const teams = {
  Company:{color:'#6046db',soft:'#eeeafd'}, Product:{color:'#147b68',soft:'#e2f5ef'},
  Growth:{color:'#b55b14',soft:'#fff0df'}, People:{color:'#b43f6b',soft:'#fde8ef'},
  Revenue:{color:'#2670b7',soft:'#e6f1fc'}
};
const divisions = ['Corporate Strategy','Product & Technology','Marketing','People & Culture','Sales & Customer Success'];
const initialGoals = [
  {id:'g1',title:'Build the category-defining AI workspace',description:'Create a product experience customers cannot imagine working without.',team:'Company',division:'Corporate Strategy',owner:'Maya Chen',initials:'MC',progress:68,status:'On track',period:'Q3 2026',parentId:null,updated:'2h ago',keyResults:[{id:'kr11',title:'Reach 45% weekly active usage',value:72},{id:'kr12',title:'Increase NPS to 62',value:64},{id:'kr13',title:'Ship 3 AI workflow capabilities',value:67}],initiatives:[{id:'in11',title:'AI command center',status:'In progress'},{id:'in12',title:'Context-aware recommendations',status:'Planned'},{id:'in13',title:'Mobile workspace refresh',status:'In progress'}]},
  {id:'g2',title:'Deliver an exceptional activation experience',description:'Help every new team reach meaningful value in their first session.',team:'Product',division:'Product & Technology',owner:'Noah Williams',initials:'NW',progress:61,status:'On track',period:'Q3 2026',parentId:'g1',updated:'Yesterday',keyResults:[{id:'kr21',title:'Reduce time-to-value below 8 minutes',value:58},{id:'kr22',title:'Raise onboarding completion to 80%',value:64}],initiatives:[{id:'in21',title:'Guided workspace setup',status:'In progress'},{id:'in22',title:'Role-based templates',status:'Planned'},{id:'in23',title:'Activation analytics',status:'In progress'}]},
  {id:'g3',title:'Create a repeatable growth engine',description:'Build efficient, measurable acquisition loops across priority segments.',team:'Growth',division:'Marketing',owner:'Sofia Patel',initials:'SP',progress:44,status:'At risk',period:'Q3 2026',parentId:'g1',updated:'3h ago',keyResults:[{id:'kr31',title:'Generate 2,500 product-qualified leads',value:48},{id:'kr32',title:'Improve organic conversion by 25%',value:40}],initiatives:[{id:'in31',title:'Customer story program',status:'In progress'},{id:'in32',title:'SEO topic clusters',status:'In progress'},{id:'in33',title:'Partner launch playbook',status:'Planned'}]},
  {id:'g4',title:'Become the best place to do career-defining work',description:'Create an environment where ambitious people thrive and grow.',team:'People',division:'People & Culture',owner:'Avery Johnson',initials:'AJ',progress:76,status:'On track',period:'Q3 2026',parentId:null,updated:'Mon',keyResults:[{id:'kr41',title:'Reach 85% engagement score',value:82},{id:'kr42',title:'Fill 90% of key roles on time',value:70}],initiatives:[{id:'in41',title:'Manager excellence program',status:'In progress'},{id:'in42',title:'Career architecture rollout',status:'Planned'},{id:'in43',title:'Hiring bar calibration',status:'Done'}]},
  {id:'g5',title:'Scale leadership capability',description:'Equip every manager to lead with clarity, empathy, and accountability.',team:'People',division:'People & Culture',owner:'Amelia Davis',initials:'AD',progress:52,status:'At risk',period:'Q3 2026',parentId:'g4',updated:'Fri',keyResults:[{id:'kr51',title:'100% manager coaching completion',value:61},{id:'kr52',title:'Increase manager effectiveness to 4.3',value:43}],initiatives:[{id:'in51',title:'Monthly manager labs',status:'In progress'},{id:'in52',title:'Leadership 360 reviews',status:'Planned'}]},
  {id:'g6',title:'Accelerate enterprise expansion',description:'Win and grow strategic accounts with a focused commercial motion.',team:'Revenue',division:'Sales & Customer Success',owner:'Ethan Brooks',initials:'EB',progress:31,status:'Off track',period:'Q3 2026',parentId:null,updated:'4h ago',keyResults:[{id:'kr61',title:'Close $1.8M enterprise ARR',value:28},{id:'kr62',title:'Grow expansion pipeline to $4M',value:34}],initiatives:[{id:'in61',title:'Enterprise account pods',status:'In progress'},{id:'in62',title:'Executive sponsor program',status:'Planned'},{id:'in63',title:'Security readiness sprint',status:'In progress'}]}
];
const statusTone={'On track':'green','At risk':'amber','Off track':'red','Not started':'gray'};
const navItems=[{icon:Home,label:'Home'},{icon:Target,label:'Goals',active:true},{icon:Activity,label:'Check-ins'},{icon:BarChart3,label:'Insights'}];
const uid=prefix=>`${prefix}${Date.now()}${Math.random().toString(16).slice(2,6)}`;
const initials=name=>name.split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,2).toUpperCase();
const health=p=>p>=60?'On track':p>=40?'At risk':'Off track';
function migrate(raw){return (raw||initialGoals).map((g,i)=>({...g,division:g.division||divisions[i%divisions.length],keyResults:(g.keyResults||[]).map((k,j)=>({...k,id:k.id||`kr${i}${j}`})),initiatives:(g.initiatives||[]).map((x,j)=>typeof x==='string'?{id:`in${i}${j}`,title:x,status:j%2?'Planned':'In progress'}:{...x,id:x.id||`in${i}${j}`})}))}

function App(){
  const [goals,setGoals]=useState(()=>{try{return migrate(JSON.parse(localStorage.getItem(STORAGE_KEY)))}catch{return initialGoals}});
  const [view,setView]=useState('Cascade'),[query,setQuery]=useState(''),[teamFilter,setTeamFilter]=useState('All teams'),[divisionFilter,setDivisionFilter]=useState('All divisions');
  const [expanded,setExpanded]=useState(new Set(['g1','g4','g6'])),[selected,setSelected]=useState(null),[modal,setModal]=useState(false),[sidebar,setSidebar]=useState(false);
  useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(goals)),[goals]);
  const visible=useMemo(()=>goals.filter(g=>(teamFilter==='All teams'||g.team===teamFilter)&&(divisionFilter==='All divisions'||g.division===divisionFilter)&&(`${g.title} ${g.owner} ${g.team} ${g.division}`).toLowerCase().includes(query.toLowerCase())),[goals,query,teamFilter,divisionFilter]);
  const avg=Math.round(goals.reduce((a,g)=>a+g.progress,0)/(goals.length||1)),onTrack=goals.filter(g=>g.status==='On track').length;
  const updateGoal=(id,data)=>setGoals(gs=>gs.map(g=>g.id===id?{...g,...data,initials:data.owner?initials(data.owner):g.initials,updated:'Just now'}:g));
  const addGoal=form=>{const id=uid('g');setGoals(gs=>[...gs,{...form,id,initials:initials(form.owner),progress:Number(form.progress),parentId:form.parentId||null,updated:'Just now',keyResults:form.keyResult?[{id:uid('kr'),title:form.keyResult,value:Number(form.progress)}]:[],initiatives:form.initiatives.split('\n').filter(Boolean).map(title=>({id:uid('in'),title,status:'Planned'}))}]);setModal(false);setSelected(id)};
  const deleteGoal=id=>{if(!window.confirm('Delete this objective? Its aligned goals will move to company level.'))return;setGoals(gs=>gs.filter(g=>g.id!==id).map(g=>g.parentId===id?{...g,parentId:null}:g));setSelected(null)};
  const toggle=id=>setExpanded(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n});
  return <div className="app-shell"><Sidebar open={sidebar} close={()=>setSidebar(false)} count={goals.length}/><main className="main">
    <header className="topbar"><button className="mobile-menu icon-button" onClick={()=>setSidebar(true)}><Menu size={20}/></button><div className="crumb"><span>Goals</span><ChevronRight size={14}/><strong>Explorer</strong></div><div className="top-actions"><button className="icon-button"><Search size={19}/></button><button className="icon-button notification"><Bell size={19}/><i/></button><div className="avatar">MC</div></div></header>
    <section className="content"><div className="hero"><div><div className="eyebrow"><Sparkles size={14}/> STRATEGY EXECUTION</div><h1>Goals Explorer</h1><p>See how every team’s work connects to what matters most.</p></div><button className="primary" onClick={()=>setModal(true)}><Plus size={18}/> New goal</button></div>
      <div className="metrics"><Metric icon={Target} label="Active goals" value={goals.length} detail={`Across ${new Set(goals.map(g=>g.division)).size} divisions`} tone="violet"/><Metric icon={Activity} label="Average progress" value={`${avg}%`} detail="Live OKR score" tone="blue"/><Metric icon={Check} label="On track" value={`${onTrack}/${goals.length}`} detail={`${Math.round(onTrack/(goals.length||1)*100)}% healthy`} tone="green"/><Metric icon={Clock3} label="Quarter remaining" value="31 days" detail="Ends Sep 30" tone="orange"/></div>
      <div className="workspace"><div className="workspace-head"><div className="view-tabs">{[[GitBranch,'Cascade'],[TreePine,'Tree'],[List,'List']].map(([Icon,name])=><button key={name} className={view===name?'active':''} onClick={()=>setView(name)}><Icon size={17}/>{name}</button>)}</div><div className="period"><button className="icon-button"><ChevronLeft size={17}/></button><CalendarDays size={16}/><b>Q3 2026</b><button className="icon-button"><ChevronRight size={17}/></button></div></div>
        <div className="toolbar"><div className="searchbox"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search goals, owners, teams, or divisions..."/>{query&&<button onClick={()=>setQuery('')}><X size={15}/></button>}</div><div className="toolbar-right"><FilterSelect icon={Users} value={teamFilter} set={setTeamFilter} first="All teams" options={Object.keys(teams)}/><FilterSelect icon={Building2} value={divisionFilter} set={setDivisionFilter} first="All divisions" options={divisions}/><button className="filter-button"><Filter size={16}/> Filters <span>{Number(teamFilter!=='All teams')+Number(divisionFilter!=='All divisions')}</span></button><button className="icon-button"><ArrowDownUp size={17}/></button></div></div>
        {view==='Cascade'&&<Cascade goals={visible} expanded={expanded} toggle={toggle} select={setSelected}/>} {view==='Tree'&&<TreeView goals={visible} select={setSelected}/>} {view==='List'&&<ListView goals={visible} select={setSelected}/>} 
      </div></section></main>
    {modal&&<GoalModal goals={goals} close={()=>setModal(false)} save={addGoal}/>} {selected&&goals.some(g=>g.id===selected)&&<GoalDrawer goal={goals.find(g=>g.id===selected)} goals={goals} close={()=>setSelected(null)} update={updateGoal} remove={deleteGoal}/>} 
  </div>
}
function FilterSelect({icon:Icon,value,set,first,options}){return <label className="select-wrap"><Icon size={16}/><select value={value} onChange={e=>set(e.target.value)}><option>{first}</option>{options.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={14}/></label>}
function Sidebar({open,close,count}){return <><aside className={`sidebar ${open?'open':''}`}><div className="brand"><div className="brand-mark"><Compass size={21}/></div><div><b>Northstar</b><span>OKR workspace</span></div><button className="mobile-close" onClick={close}><X/></button></div><nav>{navItems.map(({icon:Icon,label,active})=><button key={label} className={active?'active':''}><Icon size={19}/><span>{label}</span>{label==='Goals'&&<em>{count}</em>}</button>)}</nav><div className="nav-label">WORKSPACE</div><nav><button><Building2 size={19}/><span>Teams</span></button><button><CalendarDays size={19}/><span>Cycles</span></button><button><LayoutDashboard size={19}/><span>Reports</span></button></nav><div className="sidebar-card"><div className="card-icon"><Zap size={17}/></div><b>Quarterly review</b><p>Your Q3 review is in 5 days. Make sure every goal is current.</p><button>Review check-ins</button></div><div className="sidebar-foot"><button><CircleHelp size={19}/>Help & resources</button><button><Settings size={19}/>Settings</button><div className="profile"><div className="avatar">MC</div><div><b>Maya Chen</b><span>Workspace admin</span></div><MoreHorizontal size={18}/></div></div></aside>{open&&<div className="scrim" onClick={close}/>}</>}
function Metric({icon:Icon,label,value,detail,tone}){return <article className="metric"><div className={`metric-icon ${tone}`}><Icon size={19}/></div><div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div></article>}
function Cascade({goals,expanded,toggle,select}){const roots=goals.filter(g=>!g.parentId||!goals.some(x=>x.id===g.parentId)),children=id=>goals.filter(g=>g.parentId===id),rows=[];roots.forEach(root=>{rows.push({g:root,level:0});if(expanded.has(root.id))children(root.id).forEach(c=>rows.push({g:c,level:1}))});return <div className="cascade table-scroll"><div className="cascade-grid header-row"><div>Name</div><div>Team</div><div>Owner</div><div>Division</div><div>Progress</div><div>Status</div><div/></div>{rows.map(({g,level})=>{const kids=children(g.id);return <div className={`cascade-grid data-row level-${level}`} key={g.id} onClick={()=>select(g.id)}><div className="goal-name" style={{paddingLeft:level*34+18}}>{kids.length?<button onClick={e=>{e.stopPropagation();toggle(g.id)}}>{expanded.has(g.id)?<ChevronDown/>:<ChevronRight/>}</button>:<span className="row-spacer"/>}<div className={`type-icon ${level?'objective':'parent'}`}>{level?<Target size={15}/>:<Flag size={15}/>}</div><div><b>{g.title}</b><small>{level?`${g.keyResults.length} key results · ${g.initiatives.length} initiatives`:`${kids.length} aligned objective${kids.length!==1?'s':''}`}</small></div></div><div><TeamPill team={g.team}/></div><div><Owner goal={g}/></div><div><Division value={g.division}/></div><div><Progress value={g.progress}/></div><div><Status value={g.status}/></div><div><Pencil size={15}/></div></div>})}{!rows.length&&<Empty/>}<button className="add-inline" onClick={()=>document.querySelector('.primary').click()}><Plus size={16}/> Add goal</button></div>}
function TreeView({goals,select}){const roots=goals.filter(g=>!g.parentId||!goals.some(x=>x.id===g.parentId));return <div className="tree-view"><div className="tree-intro"><GitBranch size={18}/><div><b>Alignment map</b><span>Follow the line from company strategy to team execution.</span></div></div><div className="tree-canvas">{roots.map(root=><div className="tree-branch" key={root.id}><GoalCard goal={root} select={select} parent/>{goals.filter(g=>g.parentId===root.id).length>0&&<div className="tree-children">{goals.filter(g=>g.parentId===root.id).map(g=><GoalCard key={g.id} goal={g} select={select}/>)}</div>}</div>)}</div>{!roots.length&&<Empty/>}</div>}
function GoalCard({goal,select,parent}){return <button className={`goal-card ${parent?'parent':''}`} onClick={()=>select(goal.id)}><div className="goal-card-top"><TeamPill team={goal.team}/><Division value={goal.division}/></div><h3>{goal.title}</h3><p>{goal.description}</p><div className="goal-card-bottom"><Owner goal={goal} compact/><Progress value={goal.progress} compact/></div></button>}
function ListView({goals,select}){return <div className="list-view"><div className="list-header"><span>Objective</span><span>Owner</span><span>Division</span><span>Cycle</span><span>Progress</span><span>Status</span></div>{goals.map(g=><button className="list-row" key={g.id} onClick={()=>select(g.id)}><div className="list-objective"><div className="type-icon objective"><Target size={15}/></div><div><b>{g.title}</b><small>{g.keyResults.length} key results · {g.initiatives.length} initiatives · Updated {g.updated}</small></div></div><Owner goal={g}/><Division value={g.division}/><span className="cycle">{g.period}</span><Progress value={g.progress}/><Status value={g.status}/></button>)}{!goals.length&&<Empty/>}</div>}
function TeamPill({team}){const t=teams[team]||teams.Company;return <span className="team-pill" style={{color:t.color,background:t.soft}}><i style={{background:t.color}}/>{team}</span>}
function Division({value}){return <span className="division-pill"><Building2 size={13}/>{value}</span>}
function Owner({goal,compact}){return <span className={`owner ${compact?'compact':''}`}><i>{goal.initials}</i>{!compact&&goal.owner}</span>}
function Progress({value,compact}){const color=value>=60?'#25a77c':value>=40?'#e7a52b':'#e05a47';return <div className={`progress ${compact?'compact':''}`}><div><i style={{width:`${value}%`,background:color}}/></div><b>{value}%</b></div>}
function Status({value}){return <span className={`status ${statusTone[value]}`}><i/>{value}</span>}
function Empty(){return <div className="empty"><Search size={26}/><b>No goals found</b><span>Try adjusting your search or filters.</span></div>}

function GoalDrawer({goal,goals,close,update,remove}){
  const [editing,setEditing]=useState(false),[draft,setDraft]=useState({...goal}),[newKr,setNewKr]=useState(''),[newInitiative,setNewInitiative]=useState('');
  const patch=(field,value)=>setDraft(d=>({...d,[field]:value}));
  const saveGoal=()=>{update(goal.id,{...draft,progress:Number(draft.progress),parentId:draft.parentId||null,status:draft.status||health(Number(draft.progress))});setEditing(false)};
  const updateKr=(id,data)=>update(goal.id,{keyResults:goal.keyResults.map(k=>k.id===id?{...k,...data}:k)}),deleteKr=id=>update(goal.id,{keyResults:goal.keyResults.filter(k=>k.id!==id)});
  const addKr=()=>{if(!newKr.trim())return;update(goal.id,{keyResults:[...goal.keyResults,{id:uid('kr'),title:newKr.trim(),value:0}]});setNewKr('')};
  const updateInitiative=(id,data)=>update(goal.id,{initiatives:goal.initiatives.map(x=>x.id===id?{...x,...data}:x)}),deleteInitiative=id=>update(goal.id,{initiatives:goal.initiatives.filter(x=>x.id!==id)});
  const addInitiative=()=>{if(!newInitiative.trim())return;update(goal.id,{initiatives:[...goal.initiatives,{id:uid('in'),title:newInitiative.trim(),status:'Planned'}]});setNewInitiative('')};
  return <><div className="drawer-scrim" onClick={close}/><aside className="drawer"><div className="drawer-head"><span className="drawer-label"><Target size={15}/> OBJECTIVE</span><div className="drawer-actions"><button className="icon-button danger-icon" title="Delete objective" onClick={()=>remove(goal.id)}><Trash2 size={17}/></button><button className="icon-button" title={editing?'Save':'Edit objective'} onClick={()=>{if(editing)saveGoal();else{setDraft({...goal});setEditing(true)}}}>{editing?<Save size={18}/>:<Pencil size={18}/>}</button><button className="icon-button" onClick={close}><X size={19}/></button></div></div>
    {editing?<div className="drawer-edit"><Field label="Objective title" full><input value={draft.title} onChange={e=>patch('title',e.target.value)}/></Field><Field label="Description" full><textarea value={draft.description} onChange={e=>patch('description',e.target.value)}/></Field><Field label="Team"><select value={draft.team} onChange={e=>patch('team',e.target.value)}>{Object.keys(teams).map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Division"><select value={draft.division} onChange={e=>patch('division',e.target.value)}>{divisions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Owner"><input value={draft.owner} onChange={e=>patch('owner',e.target.value)}/></Field><Field label="Cycle"><select value={draft.period} onChange={e=>patch('period',e.target.value)}><option>Q3 2026</option><option>Q4 2026</option><option>Annual 2026</option></select></Field><Field label="Align to"><select value={draft.parentId||''} onChange={e=>patch('parentId',e.target.value)}><option value="">Company-level goal</option>{goals.filter(g=>g.id!==goal.id&&g.parentId!==goal.id).map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></Field><Field label="Progress"><input type="number" min="0" max="100" value={draft.progress} onChange={e=>patch('progress',e.target.value)}/></Field><Field label="Health"><select value={draft.status} onChange={e=>patch('status',e.target.value)}>{Object.keys(statusTone).map(x=><option key={x}>{x}</option>)}</select></Field><div className="edit-actions"><button className="secondary" onClick={()=>{setDraft({...goal});setEditing(false)}}>Cancel</button><button className="primary" onClick={saveGoal}><Save size={16}/> Save objective</button></div></div>:<><div className="drawer-title"><div className="title-pills"><TeamPill team={goal.team}/><Division value={goal.division}/></div><h2>{goal.title}</h2><p>{goal.description}</p></div><div className="drawer-meta"><div><span>Owner</span><Owner goal={goal}/></div><div><span>Cycle</span><b><CalendarDays size={15}/>{goal.period}</b></div><div><span>Health</span><Status value={goal.status}/></div></div><section className="drawer-section"><div className="section-head"><div><b>Overall progress</b><span>Update progress to keep your team aligned.</span></div><strong>{goal.progress}%</strong></div><input className="range" type="range" min="0" max="100" value={goal.progress} onChange={e=>update(goal.id,{progress:Number(e.target.value),status:health(Number(e.target.value))})}/></section></>}
    <section className="drawer-section"><div className="section-head"><div><b>Key results</b><span>Create, update, and remove measurable outcomes.</span></div></div><div className="kr-list">{goal.keyResults.map((kr,i)=><div className="kr crud-row" key={kr.id}><div className="kr-index">{i+1}</div><div className="crud-content"><input value={kr.title} onChange={e=>updateKr(kr.id,{title:e.target.value})}/><div className="kr-progress-edit"><input type="range" min="0" max="100" value={kr.value} onChange={e=>updateKr(kr.id,{value:Number(e.target.value)})}/><b>{kr.value}%</b></div></div><button className="delete-small" onClick={()=>deleteKr(kr.id)}><Trash2 size={15}/></button></div>)}</div><div className="inline-create"><input value={newKr} onChange={e=>setNewKr(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addKr()} placeholder="Add a measurable key result..."/><button onClick={addKr}><Plus size={16}/> Add</button></div></section>
    <section className="drawer-section"><div className="section-head"><div><b>Initiatives</b><span>Manage the work driving this objective.</span></div></div><div className="initiative-list">{goal.initiatives.map(x=><div className="initiative-crud" key={x.id}><span><Zap size={15}/></span><input value={x.title} onChange={e=>updateInitiative(x.id,{title:e.target.value})}/><select value={x.status} onChange={e=>updateInitiative(x.id,{status:e.target.value})}><option>Planned</option><option>In progress</option><option>Done</option><option>Blocked</option></select><button className="delete-small" onClick={()=>deleteInitiative(x.id)}><Trash2 size={15}/></button></div>)}</div><div className="inline-create"><input value={newInitiative} onChange={e=>setNewInitiative(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addInitiative()} placeholder="Add an initiative..."/><button onClick={addInitiative}><Plus size={16}/> Add</button></div></section>
  </aside></>}
function Field({label,full,children}){return <label className={full?'full':''}><span>{label}</span>{children}</label>}
function GoalModal({goals,close,save}){const [form,setForm]=useState({title:'',description:'',team:'Product',division:'Product & Technology',owner:'',period:'Q3 2026',progress:0,status:'Not started',parentId:'',keyResult:'',initiatives:''}),change=e=>setForm({...form,[e.target.name]:e.target.value}),submit=e=>{e.preventDefault();if(form.title&&form.owner)save(form)};return <div className="modal-wrap"><div className="modal"><div className="modal-head"><div><span className="drawer-label"><Sparkles size={14}/> NEW OBJECTIVE</span><h2>Create a goal</h2><p>Define the outcome, owner, division, and work that will move it forward.</p></div><button className="icon-button" onClick={close}><X/></button></div><form onSubmit={submit}><Field label="Objective title" full><input autoFocus required name="title" value={form.title} onChange={change} placeholder="What do you want to accomplish?"/></Field><Field label="Description" full><textarea name="description" value={form.description} onChange={change} placeholder="Why does this objective matter?"/></Field><Field label="Team"><select name="team" value={form.team} onChange={change}>{Object.keys(teams).map(t=><option key={t}>{t}</option>)}</select></Field><Field label="Division"><select name="division" value={form.division} onChange={change}>{divisions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Owner"><input required name="owner" value={form.owner} onChange={change} placeholder="Full name"/></Field><Field label="Cycle"><select name="period" value={form.period} onChange={change}><option>Q3 2026</option><option>Q4 2026</option><option>Annual 2026</option></select></Field><Field label="Align to"><select name="parentId" value={form.parentId} onChange={change}><option value="">Company-level goal</option>{goals.map(g=><option value={g.id} key={g.id}>{g.title}</option>)}</select></Field><Field label="Starting progress"><input type="number" name="progress" min="0" max="100" value={form.progress} onChange={change}/></Field><Field label="First measurable key result" full><input name="keyResult" value={form.keyResult} onChange={change} placeholder="e.g. Increase activation rate from 42% to 65%"/></Field><Field label="Initiatives · one per line" full><textarea name="initiatives" value={form.initiatives} onChange={change} placeholder={'Redesign onboarding flow\nLaunch guided templates'}/></Field><div className="form-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" type="submit"><Plus size={17}/> Create goal</button></div></form></div></div>}
export default App;
